### ISSUE TITLE
 Ask about parameter setting 

### ISSUE THREAD

**Issue by v3551G** [YyzHarry/multi-domain-imbalance#5]
Hello,
     I am pleased to read your paper published at ECCV 2022. We noticed that  in multi-domain environment, the number of training samples contained in each domain/environment  varies significantly, and the parameter 'batch_size' means the number of samples sampled from each domain. So, how is parameter 'CHECKPOINT_FREQ' (i.e the parameter Epoch e in the pseudo-code ) set?  It depends on the largest dataset or the smallest dataset?   Can you tell us something about your experience? 

Thank you very much!

**Comment by YyzHarry** [comment]
Hi - thanks for your interest in our paper. As you said, different domains contain different number of samples, so in practice, during  training we use [InfiniteDataLoader](https://github.com/YyzHarry/multi-domain-imbalance/blob/main/mdlt/dataset/fast_dataloader.py#L15) which yields an infinite stream of data (looped over again if all samples have been iterated once) for each domain. Therefore it avoids the problem of inconsistent number of samples per domain.

Regarding `CHECKPOINT_FREQ`, since we use the InfiniteDataLoader, it is not related to # of samples in each domain. In principle you can set to whatever numbers you would like; a smaller value would lead to a finer-grained evaluation (which potentially could deliver better results), but will also increase the overhead (as you do the evaluation more frequently, which requires to loop over all validation data each time).
